// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Config {
  final String dbPath;
  final List<String> origin;
  final String bindAddress;
  final int port;
  final int minHeight;
  final String certPath;
  final String keyPath;

  const Config({
    required this.dbPath,
    required this.origin,
    required this.bindAddress,
    required this.port,
    required this.minHeight,
    required this.certPath,
    required this.keyPath,
  });

  @override
  int get hashCode =>
      dbPath.hashCode ^
      origin.hashCode ^
      bindAddress.hashCode ^
      port.hashCode ^
      minHeight.hashCode ^
      certPath.hashCode ^
      keyPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          origin == other.origin &&
          bindAddress == other.bindAddress &&
          port == other.port &&
          minHeight == other.minHeight &&
          certPath == other.certPath &&
          keyPath == other.keyPath;
}
