// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_layer`, `env_layer`

Future<void> setConfig({required Config config}) =>
    RustLib.instance.api.crateApiInitSetConfig(config: config);

Future<void> config() => RustLib.instance.api.crateApiInitConfig();
