name: Dynamic runner workflow
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner to use"
        type: string
        required: true
      ext:
        description: "File extension"
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup PATH
        run: |
          echo "/root/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo build --release
        env:
          RUSTUP_HOME: /root/.rustup
      - name: Rename bin package
        id: package
        run: |
          mv target/release/lwdproxy_rs lwdproxy_rs.${{ github.event.inputs.ext }}
          echo "PKG_PATH=$PWD/lwdproxy_rs.${{ github.event.inputs.ext }}" >> $GITHUB_OUTPUT
      - name: Upload bin artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.package.outputs.PKG_PATH }}
