name: Build and Release Linux Debian Package

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - lwdproxy-v*

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --release
        env:
          RUSTUP_HOME: /root/.rustup
      - name: Rename bin package
        id: package
        run: |
          mv target/release/lwdproxy_rs lwdproxy_rs_x86_64
          echo "PKG_PATH=$PWD/lwdproxy_rs_x86_64" >> $GITHUB_OUTPUT
      - name: Create Release
        if: startsWith(github.ref_name, 'lwdproxy-v')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.PKG_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
