name: Build and Release Linux Debian Package on ARM64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/zkool-ci-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup PATH
        run: |
          echo "/root/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo build --release
        env:
          RUSTUP_HOME: /root/.rustup
      - name: Rename deb package
        id: package
        run: |
          mv target/release/lwdproxy_rs lwdproxy_rs
          echo "PKG_PATH=$PWD/lwdproxy_rs" >> $GITHUB_OUTPUT
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.package.outputs.PKG_PATH }}
