name: ci

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  release-please:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release-please.yml
    secrets: inherit

  build:
    if: "!contains(github.head_ref, 'release-please--')"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      runner: ubuntu-latest
      ext: x86_64
